[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Eric Burden <eric.w.burden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
itertools = "0.10.1"
text_io="0.1.9"
